### PR TITLE
#4 Fixed duplicated constant

### PR DESCRIPTION
**Pull request by andreiashu**

### CODE REVIEW

**Comment by sharique** [comment]
This looks good to me.

**Comment by vijaycs85** [comment]
good catch @andreiashu, guess it's introduced recently by https://github.com/Capgemini/drupal_symfony_inject/issues/2

**Comment by andreiashu** [comment]
Yeah not a big deal but good to keep things consistent :)

**Comment by jamsilver** [comment]
Ahh - you did. Months ago. Amazing.

FYI - this solves a WSOD for the first page load after every cache-clear.

Thanks @andreiashu!

**Pull request merged**
